set (PLIBSYS_THREAD_MODEL beos)
set (PLIBSYS_IPC_MODEL none)
set (PLIBSYS_TIME_PROFILER_MODEL beos)
set (PLIBSYS_DIR_MODEL posix)
set (PLIBSYS_LIBRARYLOADER_MODEL beos)
set (PLIBSYS_RWLOCK_MODEL general)

set (PLIBSYS_PLATFORM_DEFINES
        -D_REENTRANT
)

set (PLIBSYS_PLATFORM_LINK_LIBRARIES root socket bind)
