set (PLIBSYS_THREAD_MODEL win)
set (PLIBSYS_IPC_MODEL win)
set (PLIBSYS_TIME_PROFILER_MODEL win)
set (PLIBSYS_DIR_MODEL win)
set (PLIBSYS_LIBRARYLOADER_MODEL win)

set (PLIBSYS_PLATFORM_LINK_LIBRARIES ws2_32)
