set (PLIBSYS_THREAD_MODEL os2)
set (PLIBSYS_IPC_MODEL os2)
set (PLIBSYS_TIME_PROFILER_MODEL os2)
set (PLIBSYS_DIR_MODEL os2)
set (PLIBSYS_RWLOCK_MODEL general)
set (PLIBSYS_LIBRARYLOADER_MODEL os2)

set (PLIBSYS_PLATFORM_LINK_LIBRARIES os2386)

set (PLIBSYS_PLATFORM_DEFINES
        -D_REENTRANT
)
