set (PLIBSYS_THREAD_MODEL posix)
set (PLIBSYS_IPC_MODEL posix)
set (PLIBSYS_TIME_PROFILER_MODEL posix)
set (PLIBSYS_DIR_MODEL posix)
set (PLIBSYS_ATOMIC_MODEL decc)
set (PLIBSYS_LIBRARYLOADER_MODEL posix)

set (PLIBSYS_PLATFORM_LINK_LIBRARIES -pthread rt)

set (PLIBSYS_PLATFORM_DEFINES
        -D_REENTRANT
        -D_XOPEN_SOURCE_EXTENDED=1
        -D_POSIX_PII_SOCKET
        -D_OSF_SOURCE
        -D_XOPEN_SOURCE=500
        -D_POSIX_SOURCE=199506L
)
