set (PLIBSYS_THREAD_MODEL atheos)
set (PLIBSYS_IPC_MODEL none)
set (PLIBSYS_TIME_PROFILER_MODEL posix)
set (PLIBSYS_DIR_MODEL posix)
set (PLIBSYS_RWLOCK_MODEL general)
set (PLIBSYS_LIBRARYLOADER_MODEL posix)

set (PLIBSYS_PLATFORM_LINK_LIBRARIES rt dl)

set (PLIBSYS_PLATFORM_DEFINES
        -D_REENTRANT
)
