set (PLIBSYS_THREAD_MODEL amiga)
set (PLIBSYS_IPC_MODEL amiga)
set (PLIBSYS_TIME_PROFILER_MODEL amiga)
set (PLIBSYS_DIR_MODEL posix)
set (PLIBSYS_LIBRARYLOADER_MODEL amiga)
set (PLIBSYS_RWLOCK_MODEL general)

set (PLIBSYS_PLATFORM_LINK_LIBRARIES auto amiga unix)

set (PLIBSYS_PLATFORM_DEFINES
        -D_REENTRANT
)
