set (PLIBSYS_THREAD_MODEL posix)
set (PLIBSYS_IPC_MODEL sysv)
set (PLIBSYS_TIME_PROFILER_MODEL posix)
set (PLIBSYS_DIR_MODEL posix)
set (PLIBSYS_LIBRARYLOADER_MODEL posix)

set (PLIBSYS_PLATFORM_LDFLAGS -L/usr/lib/threads)
set (PLIBSYS_PLATFORM_LINK_LIBRARIES c_r -pthread)

set (PLIBSYS_PLATFORM_DEFINES
        -D_REENTRANT
        -D_THREAD_SAFE
)
