set (PLIB_THREAD_MODEL posix)
set (PLIB_IPC_MODEL sysv)
set (PLIB_TIME_PROFILER_MODEL solaris)
set (PLIB_DIR_MODEL posix)

set (PLIB_PLATFORM_LINK_LIBRARIES xnet rt -pthread)

set (PLIB_PLATFORM_DEFINES
        -D_REENTRANT
        -D_THREAD_SAFE
        -D_XOPEN_SOURCE_EXTENDED=1
)
