set (PLIBSYS_THREAD_MODEL win)
set (PLIBSYS_IPC_MODEL win)
set (PLIBSYS_TIME_PROFILER_MODEL win)
set (PLIBSYS_DIR_MODEL win)
set (PLIBSYS_LIBRARYLOADER_MODEL win)

set (PLIBSYS_PLATFORM_CFLAGS "-w-8065 -w-8008 -w-8057 -w-8059 -w-8066 -w-8004")
set (PLIBSYS_PLATFORM_LINK_LIBRARIES ws2_32)
