set (PLIB_THREAD_MODEL posix)
set (PLIB_IPC_MODEL posix)
set (PLIB_TIME_PROFILER_MODEL posix)
set (PLIB_DIR_MODEL posix)

set (PLIB_PLATFORM_LINK_LIBRARIES socket)

set (PLIB_PLATFORM_DEFINES
        -D_REENTRANT
        -D_POSIX_THREAD_SAFE_FUNCTIONS
)
