set (PLIBSYS_THREAD_MODEL win)
set (PLIBSYS_IPC_MODEL win)
set (PLIBSYS_TIME_PROFILER_MODEL win)
set (PLIBSYS_DIR_MODEL win)

if (NOT CMAKE_SIZEOF_VOID_P)
    set (CMAKE_SIZEOF_VOID_P 4)
endif()

set (PLIBSYS_PLATFORM_LINK_LIBRARIES ws2_32)
