set (PLIB_THREAD_MODEL win)
set (PLIB_IPC_MODEL win)
set (PLIB_TIME_PROFILER_MODEL win)
set (PLIB_DIR_MODEL win)

if (NOT CMAKE_SIZEOF_VOID_P)
    set (CMAKE_SIZEOF_VOID_P 4)
endif()

set (PLIB_PLATFORM_LINK_LIBRARIES ws2_32)
